# Redo the experiments with the original DESSI DATASET

In [44]:
import pandas as pd

## Dessi Original

In [45]:
Train_dessi = pd.read_csv('train.csv', low_memory=False)
Train_dessi_labels = pd.read_csv('train_labels.csv', low_memory=False)

In [116]:
em = Train_dessi.filter(regex='email').columns

In [117]:
Train_dessi[em]

,customer_email,family_email,family_contact_email,emailid,contact_email,useremail,email_sid,emailladdresssid,email_address_sid,customer_email.1,...,customer_email.32,email_sid.72,family_email.71,email_address_sid.39,email_address_sid.40,email_id.45,family_email.72,loweredemail.76,contact_email.76,email_address.29
0,danica-dereta3@xnet.hr,152691757/5,w-ford5592@castro-rojas.ly,evelyn-gallo@gmail.com,SEVHCX88V88T507S,adale@yahoo.com,b.cooper@yahoo.com,ed2802@t.ht.hr,ml@gmail.com,mwagner@raymond.us,...,ebrown7@scott.store,k-winter9@bell-bullock.ly,444.648.3582x66645,en@hotmail.com,"Ridge Road, New Fairfield, United States of Am...","Joyce Kilmer Road rd. on number 51 in Boston, ...",aiden-plascencia6@martinez-nelson.website,nikola-vesligaj5@gmail.com,+60 (5075) 63 72,m-winter6062@beasley-schroeder.org
1,iriskuckovecki1@zagreb.hr,+45 (65) 90179-6903,m.shea@miller.store,m-marcius55@frketic.org,k.b@campos.com,s-maricic@zagreb.hr,siena-parker716@ross.xyz,aaronmagallanes@knapp.site,e-r@castro-sutton.store,m.lampe4@white.us,...,a.w@gray-wilson.store,brooklyn-harvey@richardson.online,4840977475,mv@yahoo.com,a.loftus@hotmail.com,e.b661@zg.t-com.hr,d-kennedy3@steele-meyer.info,raina-silva@yahoo.com,84 2297-2142,sbechtel0@espinoza-fletcher.ly
2,l-j817@burton.info,044 209 709,x-solano8@rosario-jackson.net,eseitz50@baker.website,dora-sobol@lisica.com.hr,f-w@yahoo.com,o-r60@marquez-lee.com,g-pearson@hotmail.com,b.mulligan46@yahoo.com,ah6@zivkovic.net,...,m.p17@vip.hr,k-adame@hotmail.com,8707733687,i.njezic@hranic.biz,carolinemartinez@clay-thomas.info,"10 Karl-von-Lutterotti-Straße, Stadt Imst, Tir...",steven-jackson77@mcdonald.info,bella-carrillo63@norris.co,2615998330,j-hale7@morris.online
3,o.d248@yahoo.com,396 09 98,l.r@hotmail.com,l-witham@ross-gibson.net,a-t@hotmail.com,emberlynrodriguez@allen-davis.us,grant-salgado@chase.org,mr27@matic.org,r-f@jordan.info,c-l@yahoo.com,...,dania.urias@villanueva.site,mc619@anderson-mueller.ly,2319057321,hana.kokot@sturlan.info,smcgrath0@yahoo.com,km@arnold.store,k-masse@lynch-anderson.net,j.jelavic@bogdan.info,+227708 200 796,sh@bender-ward.store
4,s-m@gmail.com,8315018329,es@hotmail.com,jonapuntar@xnet.hr,o.walker@yahoo.com,z-s@taylor-king.org,d.m@inet.hr,gabrijela.mavar45@grzetic.info,hrobledo8101@pierce-andrews.website,samuel-barlow@hotmail.com,...,elizabeth.pace6828@walker-garcia.net,s.a45@wu-morris.site,13103983711,ra@gomez-rios.org,mc619@anderson-mueller.ly,"Weeks Lane, Killingly, United States of America",leena.moore@pace.online,quinn-barajas8@graham-stewart.info,13417908187,klarson19@solomon-ramos.online
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,williamhernandez@sims.online,040 271 809,lexiterrell689@hotmail.com,i-p@inet.hr,j.klasic6@vip.hr,d.markle@alvarado.online,hc4117@rogers.co,a.foster8@garner-elliott.site,nperica@gabud.com.hr,caleb-mulder59@yahoo.com,...,daleyza-richardson@lynch.ly,aleksandarcvitkovic@t.ht.hr,112 212 742 107,a.m7@cvitan.net,h.w401@grimes.com,"Chimney Hill Road rd. on number 15 in Sherman,...",h-griffith@white-le.com,e.g4@bezic.info,15219702618,barica-andrijanic@globalnet.hr
96,c-allen@gmail.com,098 0141 161,ldelacruz@mcmillan-carter.ly,terence-mcguire153@yahoo.com,IQTJAS94P44S573H,averyblair@dougherty.site,diana.collazo@reed-rodriguez.co,maxxzhu30@griffin-neal.us,luca.satrak80@vip.hr,z.v3@yahoo.hr,...,lb@hotmail.com,s-nieto@gmail.com,+1-069-803-9973x361,jb@gmail.com,"Via Antonio Vivaldi, Imola, Emilia-Romagna","13 Rakoczego, Przemyśl, 37-700 województwo pod...",w-w@steele.biz,dujesimic878@lojen.com.hr,1 (995) 849-0724,d-z0@hotmail.com
97,a.d@lowe.us,001-840-103-9938x0335,tomislav.buneta@segovic.net,crodriguez@hotmail.com,jmcgrath6@bryant.co,j.seric@doncevic.biz,as43@logan.store,a.h@rodriguez-martinez.net,hoconnor976@campbell-robinson.co,mc2@vip.hr,...,harrisonjackson2@yahoo.com,s.kaminski@gmail.com,8218888409,l-cepelja@ricko.biz,sebastian-waldrop@snyder-phillips.store,m.m6@conner.biz,m.lefebvre725@holmes-cunningham.online,z-j38@kopjar.biz,'+724-1701-7779,lstephens63@yahoo.com
98,n.daugherty61@hotmail.com,371098922/5,olivia.nesbitt@hotmail.com,ilendic5040@yahoo.hr,FZEILJ84N55K212U,e.kolaric@zugec.net,n.turner21@cohen-lopez.co,tlewandowski@yahoo.com,brynlee.russell3415@yahoo.com,darko-zaknic54@jovanovac.info,...,emahorvatek@yahoo.com,n.palmer7897@yahoo.com,+55 (041) 2192-6944,isaiahlawson20@joseph.ly,"Via Noel Quintavalle 30, Ferrara 44100, Emilia...","408 Front Street, Weymouth, Massachusetts 0218...",tbennett3590@sanders-williams.ly,i-tetkic8612@jurjevic.com.hr,9223 9538 / 1208,milan.bicanic9036@matijas.info
99,z-craven4898@hotmail.com,+55 21 7156 2829,marijamatic@mihalic.hr,j-winkelman@rose.biz,NTIKRH68G29T640B,i.thorne@williams.com,sariyah-stephenson69@harrison-nichols.biz,abner.cifuentes@mitchell.co,jamiyah-ehlers26@hotmail.com,amoran347@hotmail.com,...,s-maricic@zagreb.hr,h.a867@simmons.xyz,2736 33 597 750,g.g5@taylor-porter.org,"5 Feldkamp, Uelsen, Niedersachsen 49843, de","King Street, Wallingford, Connecticut, United ...",tb@vip.hr,k.lofton95@vincent.online,5126840399,darion-saldivar917@yahoo.com

In [118]:
column_positions1 = []
for i in em:
        column_position1 = Train_dessi.columns.get_loc(i)
        column_positions1.append(column_position1)

column_positions1

[19,
 21,
 82,
 83,
 115,
 155,
 183,
 198,
 211,
 217,
 218,
 263,
 279,
 281,
 290,
 310,
 325,
 341,
 347,
 376,
 387,
 419,
 424,
 429,
 433,
 440,
 458,
 463,
 467,
 487,
 490,
 492,
 503,
 505,
 515,
 526,
 533,
 547,
 585,
 611,
 627,
 630,
 685,
 690,
 726,
 739,
 743,
 771,
 772,
 784,
 787,
 790,
 794,
 798,
 799,
 823,
 840,
 892,
 896,
 926,
 929,
 932,
 947,
 952,
 987,
 994,
 1012,
 1024,
 1040,
 1053,
 1079,
 1097,
 1149,
 1193,
 1197,
 1219,
 1225,
 1227,
 1236,
 1258,
 1284,
 1334,
 1401,
 1428,
 1443,
 1501,
 1522,
 1535,
 1578,
 1602,
 1619,
 1636,
 1655,
 1656,
 1657,
 1668,
 1672,
 1678,
 1687,
 1699,
 1702,
 1713,
 1717,
 1747,
 1753,
 1785,
 1809,
 1814,
 1839,
 1861,
 1868,
 1874,
 1934,
 1954,
 1974,
 1991,
 2001,
 2011,
 2018,
 2050,
 2077,
 2078,
 2080,
 2101,
 2110,
 2145,
 2148,
 2158,
 2161,
 2183,
 2203,
 2204,
 2218,
 2222,
 2257,
 2305,
 2314,
 2321,
 2327,
 2329,
 2331,
 2350,
 2356,
 2366,
 2369,
 2434,
 2453,
 2485,
 2506,
 2578,
 2585,
 2608,
 2609,
 2619,
 2622,
 2647,
 2681,
 2708,
 2720,
 2724,
 2732,
 2763,
 2769,
 2800,
 2805,
 2831,
 2832,
 2855,
 2861,
 2940,
 2951,
 2955,
 2974,
 2989,
 3016,
 3020,
 3031,
 3098,
 3110,
 3144,
 3151,
 3254,
 3263,
 3264,
 3293,
 3325,
 3374,
 3390,
 3434,
 3438,
 3442,
 3444,
 3452,
 3462,
 3492,
 3510,
 3560,
 3607,
 3609,
 3619,
 3665,
 3666,
 3698,
 3727,
 3739,
 3770,
 3776,
 3803,
 3852,
 3857,
 3869,
 3947,
 4012,
 4043,
 4097,
 4099,
 4103,
 4119,
 4122,
 4135,
 4138,
 4147,
 4150,
 4183,
 4188,
 4200,
 4205,
 4211,
 4228,
 4229,
 4258,
 4288,
 4333,
 4344,
 4389,
 4390,
 4391,
 4413,
 4423,
 4441,
 4451,
 4456,
 4496,
 4515,
 4520,
 4579,
 4595,
 4623,
 4635,
 4648,
 4653,
 4663,
 4664,
 4667,
 4749,
 4758,
 4767,
 4771,
 4778,
 4873,
 4905,
 4960,
 4969,
 4989,
 4992,
 5078,
 5093,
 5102,
 5108,
 5142,
 5145,
 5161,
 5207,
 5243,
 5278,
 5292,
 5316,
 5339,
 5388,
 5396,
 5472,
 5488,
 5515,
 5537,
 5539,
 5598,
 5639,
 5653,
 5669,
 5681,
 5715,
 5729,
 5764,
 5810,
 5824,
 5830,
 5831,
 5835,
 5856,
 5874,
 5887,
 5895,
 5955,
 5972,
 5987,
 5990,
 6016,
 6024,
 6061,
 6068,
 6090,
 6116,
 6125,
 6134,
 6143,
 6151,
 6163,
 6175,
 6187,
 6257,
 6259,
 6268,
 6306,
 6322,
 6326,
 6327,
 6329,
 6352,
 6355,
 6371,
 6395,
 6400,
 6418,
 6429,
 6435,
 6447,
 6482,
 6485,
 6488,
 6491,
 6509,
 6511,
 6515,
 6518,
 6525,
 6546,
 6549,
 6551,
 6615,
 6640,
 6648,
 6651,
 6653,
 6673,
 6682,
 6691,
 6692,
 6704,
 6714,
 6724,
 6731,
 6761,
 6764,
 6838,
 6850,
 6855,
 6856,
 6862,
 6872,
 6876,
 6878,
 6937,
 6950,
 6976,
 6984,
 7003,
 7061,
 7066,
 7100,
 7112,
 7118,
 7120,
 7136,
 7180,
 7188,
 7282,
 7292,
 7318,
 7328,
 7337,
 7345,
 7361,
 7395,
 7398,
 7400,
 7436,
 7495,
 7508,
 7531,
 7558,
 7559,
 7577,
 7578,
 7586,
 7590,
 7608,
 7635,
 7636,
 7678,
 7679,
 7686,
 7691,
 7701,
 7710,
 7716,
 7717,
 7722,
 7729,
 7731,
 7806,
 7833,
 7842,
 7846,
 7875,
 7880,
 7940,
 7965,
 7972,
 7981,
 7982,
 7999,
 8022,
 8023,
 8036,
 8105,
 8131,
 8139,
 8176,
 8184,
 8192,
 8208,
 8235,
 8277,
 8309,
 8330,
 8342,
 8361,
 8373,
 8383,
 8399,
 8456,
 8458,
 8474,
 8476,
 8514,
 8517,
 8523,
 8558,
 8638,
 8651,
 8658,
 8664,
 8682,
 8698,
 8719,
 8739,
 8756,
 8794,
 8798,
 8799,
 8821,
 8871,
 8881,
 8887,
 8905,
 8922,
 8934,
 8953,
 8974,
 8997,
 9014,
 9030,
 9057,
 9067,
 9082,
 9083,
 9085,
 9097,
 9129,
 9136,
 9142,
 9153,
 9178,
 9235,
 9250,
 9288,
 9314,
 9318,
 9321,
 9342,
 9435,
 9467,
 9469,
 9485,
 9536,
 9544,
 9639,
 9644,
 9651,
 9661,
 9670,
 9671,
 9712,
 9738,
 9754,
 9769,
 9775,
 9783,
 9798,
 9845,
 9868,
 9877,
 9881,
 9891,
 9899,
 9901,
 9935,
 9947,
 9953,
 9960,
 9998,
 10034,
 10056,
 10066,
 10071,
 10082,
 10103,
 10111,
 10125,
 10151,
 10157,
 10167,
 10171,
 10175,
 10180,
 10186,
 10194,
 10195,
 10205,
 10249,
 10265,
 10267,
 10273,
 10283,
 10296,
 10350,
 10356,
 10377,
 10390,
 10443,
 10505,
 10520,
 10543,
 10555,
 10562,
 10581,
 10583,
 10593,
 10615,
 10618,
 10621,
 10634,
 10640,
 10662,
 10665,
 10696,
 10702,
 10709,
 10713,
 10718,
 10737,
 10750,
 10799,
 10812,
 10833,
 10842,
 10852,
 10879,
 10897,
 10932,
 10939,
 10947,
 10957,
 10984,
 10990,
 11001,
 11079,
 11095,
 11116,
 11155,
 11185,
 11211,
 11263,
 11270,
 11282,
 11289,
 11318,
 11361,
 11375,
 11386,
 11409,
 11469,
 11487,
 11505,
 11565,
 11587,
 11594,
 11605,
 11615,
 11624,
 11635,
 11659,
 11668,
 11678,
 11683,
 11685,
 11701,
 11752,
 11764,
 11772,
 11814,
 11822,
 11850,
 11866,
 11872,
 11886,
 11891,
 11900,
 11950,
 11964,
 11971,
 11980,
 12006,
 12051,
 12115,
 12123,
 12129,
 12134,
 12160,
 12173,
 12178,
 12196,
 12204,
 12208,
 12218,
 12269,
 12280,
 12294,
 12306,
 12362,
 12366,
 12377,
 12378,
 12465,
 12466,
 12484,
 12497,
 12511,
 12527,
 12580,
 12586,
 12612,
 12613,
 12614,
 12638,
 12641,
 12647,
 12668,
 12670,
 12675,
 12679,
 12708,
 12710,
 12721,
 12745,
 12749,
 12761,
 12768,
 12804,
 12808,
 12819,
 12833,
 12842,
 12863,
 12864,
 12869,
 12871,
 12890,
 12923,
 12961,
 12982,
 12993,
 13010,
 13034,
 13065,
 13073,
 13089,
 13092,
 13096,
 13113,
 13120,
 13129,
 13141,
 13143,
 13145,
 13161,
 13176,
 13218,
 13279,
 13320,
 13367,
 13368,
 13391,
 13428,
 13492,
 13508,
 13509,
 13510,
 13527,
 13560,
 13574,
 13610,
 13631,
 13666,
 13668,
 13714,
 13737,
 13750,
 13764,
 13765,
 13786,
 13790,
 13823,
 13855,
 13862,
 13868,
 13872,
 13882,
 13895,
 13911,
 13917,
 13931,
 13970,
 14016,
 14069,
 14096,
 14114,
 14115,
 14117,
 14132,
 14135,
 14172,
 14189,
 14252,
 14295,
 14329,
 14367,
 14411,
 14421,
 14430,
 14490,
 14517,
 14582,
 14591,
 14665,
 14681,
 14684,
 14691,
 14700,
 14728,
 14732,
 14734,
 14754,
 14775,
 14784,
 14785,
 14797,
 14801,
 14822,
 14864,
 14868,
 14888,
 14889,
 14903,
 14911,
 14937,
 14938,
 14985,
 14991,
 14998,
 15012,
 15025,
 15044,
 15047,
 15065,
 15080,
 15082,
 15109,
 15110,
 15116,
 15138,
 15161,
 15165,
 15166,
 15181,
 15248,
 15259,
 15279,
 15281,
 15293,
 15301,
 15309,
 15322,
 15333,
 15366,
 15370,
 15392,
 15403,
 15411,
 15413,
 15421,
 15422,
 15424,
 15428,
 15441,
 15449,
 15500,
 15512,
 15532,
 15537,
 15538,
 15543,
 15551,
 15567,
 15577,
 15582,
 15585,
 15635,
 15656,
 15660,
 15661,
 15677,
 15689,
 15691,
 15706,
 15724,
 15745,
 15754,
 15840,
 15868,
 15888,
 15894,
 15901,
 15947,
 15954,
 15956,
 15959,
 15965,
 15972,
 15986,
 15995,
 16027,
 16081,
 16086,
 16113,
 16121,
 16122,
 16127,
 16152,
 16159,
 16193,
 16197,
 16200,
 16202,
 16208,
 16225,
 16258,
 16289,
 16319,
 16326,
 16340,
 16392,
 16431,
 16489,
 16491,
 16500,
 16515,
 16533,
 16555,
 16573,
 16578,
 16625,
 16636,
 16668,
 16686,
 16704,
 16782,
 16803,
 16808,
 16815,
 16846,
 16865,
 16882,
 16979,
 16990,
 17008,
 17025,
 17094,
 17095,
 17103,
 17104,
 17123,
 17126,
 17136,
 17138,
 17144,
 17145,
 17151,
 17194,
 17201,
 17209,
 17216,
 17218,
 17263,
 17292,
 17293,
 17306,
 17312,
 17332,
 17431,
 17525,
 17555,
 17562,
 17596,
 17638,
 17643,
 17648,
 17650,
 17670,
 17692,
 17702,
 17705,
 17736,
 17744,
 17757,
 17785,
 17793,
 17809,
 17810,
 17830,
 17839,
 17884,
 17900,
 17915,
 17925,
 17956,
 17970,
 17978,
 17987,
 18014,
 18038,
 18050,
 18073,
 18089,
 18092,
 18112,
 18122,
 18153,
 18158,
 18164,
 18168,
 18178,
 18197,
 18219,
 18243,
 18258,
 18283,
 18315,
 18335,
 18346,
 18351,
 18361,
 18369,
 18393,
 18417,
 18423,
 18432,
 18454,
 18461,
 18470,
 ...]

In [119]:
selected_rows1 = Train_dessi_labels.iloc[column_positions1]

In [121]:
selected_rows1.loc[selected_rows1['Label']=='personal']

      Original labels     Label
19              Email  personal
21       Phone_number  personal
82              Email  personal
83              Email  personal
115         Email,NIN  personal
...               ...       ...
18670   Email,Address  personal
18690           Email  personal
18735           Email  personal
18746    Phone_number  personal
18796           Email  personal

[1020 rows x 2 columns]

In [94]:
# Select columns that contain a specific substring,
columns_with_char = Train_dessi.filter(regex='gen').columns
print(columns_with_char)

Index(['gen type', 'genderclass', 'gender_specific', 'gender identity',
       'gender', 'gender related', 'gender_id', 'gender.1', 'gender.2',
       'gender classification', 'gender.3', 'mgenhncrigun', 'gender.4',
       'gender.5', 'rfgenvjvxfgv', 'genderidentity', 'genderid', 'genderid.1',
       'gender specific', 'gender_id.1', 'genderid.2', 'gen type.1',
       'gender.6', 'gender related.1', 'genderid.3', 'genderid.4',
       'genderid.5', 'gender type', 'gender.7', 'gender_id.2', 'gender.8',
       'gender_id.3', 'gender.9', 'gender.10', 'gender identity.1', 'gen_type',
       'genderid.6', 'gender.11', 'gender.12', 'gender_id.4', 'gendertype',
       'genderid.7', 'gender.13', 'sort of gender', 'genderid.8',
       'gender identity.2', 'generated passport nbr', 'gender related.2',
       'gender_id.5', 'genderid.9', 'gender_id.6', 'edenfdzbgenz', 'gender.14',
       'gender.15', 'gender.16', 'genderid.10', 'gender_id.7',
       'gender classification.1', 'gender.17', 'genderid.11', 'genderid.12',
       'genderid.13', 'genderid.14', 'gender_id.8', 'genderid.15',
       'genderid.16', 'gender_id.9', 'gender specific.1', 'gender class'],
      dtype='object')

In [95]:
Train_dessi[columns_with_char]

,gen type,genderclass,gender_specific,gender identity,gender,gender related,gender_id,gender.1,gender.2,gender classification,...,genderid.11,genderid.12,genderid.13,genderid.14,gender_id.8,genderid.15,genderid.16,gender_id.9,gender specific.1,gender class
0,Male,Demienby,Trigender,F,1,Female,no,Muško,no,Moški,...,0,1,F,M,0,1,NB,NB,M,Gender diverse
1,Female,trans men,Feminine-of-center,M,1,Female,yes,Muško,yes,Ženski,...,0,1,M,NB,1,1,F,F,M,Female
2,Male,MAAB,Third gender,F,1,Male,yes,Neodređeno,no,Ženski,...,1,-1,F,M,0,0,M,NB,M,Gender diverse
3,Male,Bigender,Male-to-female,F,1,Male,no,Muško,no,Ženski,...,1,1,M,F,0,0,F,NB,M,Male
4,Male,F,Female Assigned At Birth,M,1,Male,yes,Muško,yes,Ženski,...,0,-1,NB,NB,0,0,NB,M,Ž,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Male,Demifemale,Transgender,M,-1,Male,no,Žensko,no,Ženski,...,1,-1,NB,M,1,0,M,F,M,Female
96,Male,Male Assigned At Birth,AFAB,M,-1,Male,no,Žensko,no,Moški,...,1,1,F,F,1,0,M,NB,Ž,Gender diverse
97,Male,Aliagender,Demifemale,M,-1,Female,no,Muško,yes,Moški,...,1,-1,F,F,0,0,M,F,M,Gender diverse
98,Male,Third gender,Demienby,M,1,Male,yes,Žensko,no,Ženski,...,1,1,NB,M,1,0,NB,NB,M,Female
99,Female,Novigender,Hijra,F,-1,Female,no,Žensko,yes,Moški,...,1,-1,M,F,1,0,NB,NB,M,Male

In [ ]:
columns_with_char

In [98]:


# Get the position of the column (e.g., 'Column2')
column_position = Train_dessi.columns.get_loc('genderclass')

In [100]:
column_positions = []
for i in columns_with_char:
        column_position = Train_dessi.columns.get_loc(i)
        column_positions.append(column_position)

column_positions

[307,
 1449,
 1585,
 1765,
 2002,
 2027,
 2379,
 2452,
 2551,
 2712,
 3398,
 3581,
 3774,
 4079,
 4141,
 4715,
 4869,
 4963,
 5057,
 5067,
 5295,
 5378,
 5483,
 6204,
 6283,
 6587,
 7018,
 7273,
 7331,
 7712,
 7734,
 7742,
 7771,
 8475,
 9564,
 9871,
 10041,
 10213,
 10514,
 11074,
 11442,
 11457,
 11757,
 11841,
 11968,
 12278,
 12370,
 13059,
 13294,
 13420,
 13843,
 14217,
 14337,
 14344,
 14555,
 14794,
 14942,
 15525,
 15581,
 15919,
 16123,
 16223,
 16240,
 16269,
 17131,
 17856,
 18225,
 18265,
 18708]

In [108]:
selected_rows = Train_dessi_labels.iloc[column_positions]

In [112]:
Train_dessi.iloc[:,2551]

0      no
1     yes
2      no
3      no
4     yes
     ...
95     no
96     no
97    yes
98     no
99    yes
Name: gender.2, Length: 100, dtype: object

In [110]:
selected_rows.loc[selected_rows['Label']=='non-personal']

      Original labels         Label
2002       Other_data  non-personal
2379       Other_data  non-personal
2551       Other_data  non-personal
3398       Other_data  non-personal
3774       Other_data  non-personal
4079       Other_data  non-personal
4869       Other_data  non-personal
4963       Other_data  non-personal
5067       Other_data  non-personal
5295       Other_data  non-personal
5483       Other_data  non-personal
6283       Other_data  non-personal
6587       Other_data  non-personal
7018       Other_data  non-personal
7331       Other_data  non-personal
7712       Other_data  non-personal
7734       Other_data  non-personal
7742       Other_data  non-personal
7771       Other_data  non-personal
8475       Other_data  non-personal
10041      Other_data  non-personal
10213      Other_data  non-personal
10514      Other_data  non-personal
11074      Other_data  non-personal
11457      Other_data  non-personal
11757      Other_data  non-personal
11968      Other_data  non-personal
13294      Other_data  non-personal
13420      Other_data  non-personal
13843      Other_data  non-personal
14337      Other_data  non-personal
14344      Other_data  non-personal
14555      Other_data  non-personal
14794      Other_data  non-personal
14942      Other_data  non-personal
15581      Other_data  non-personal
15919      Other_data  non-personal
16123      Other_data  non-personal
16223      Other_data  non-personal
16240      Other_data  non-personal
16269      Other_data  non-personal
17131      Other_data  non-personal
17856      Other_data  non-personal
18225      Other_data  non-personal

In [ ]:
Test_dessi_labels['Label']

          Original labels         Label
0                   Email      personal
1            Phone_number      personal
2                   Email      personal
3            Phone_number      personal
4                  Person      personal
...                   ...           ...
6267          Geolocation  non-personal
6268           Other_data  non-personal
6269                  NIN      personal
6270  Geolocation,Address      personal
6271                 Date  non-personal

[6272 rows x 2 columns]

In [46]:
Test_dessi = pd.read_csv('test.csv', low_memory=False)
Test_dessi_labels = pd.read_csv('test_labels.csv', low_memory=False)

In [47]:
dev_dessi = pd.read_csv('dev.csv', low_memory=False)
dev_dessi_labels = pd.read_csv('dev_labels.csv', low_memory=False)

In [48]:
print(Train_dessi.shape)
print(dev_dessi.shape)
print(Test_dessi.shape)

(100, 18816)
(100, 6272)
(100, 6272)

In [49]:
# Define the mapping of classes to "personal" and "non-personal"
class_mapping = {
    "Other data": "non-personal",
    "Phone_number": "personal",
    "Address": "personal",
    "Person": "personal",
    "Email": "personal",
    "NIN": "personal",
    "Date": "non-personal",
    "Organization": "non-personal",
    "GPE": "non-personal",
    "Geolocation": "non-personal",
    "SWIFT/BIC": "personal",
    "IBAN": "personal",
    "Passport": "personal",
    "Religion": "personal",
    "CCN": "personal",
    "ID_Card": "personal",
    "Sexuality": "personal",
    "Gender": "personal",
    "Nationality": "personal",
    "Race": "personal"
}

# # Function to classify a given class or combination of classes into "personal" or "non-personal"
# def classify_data(data_classes):
#     if not isinstance(data_classes, str):  # Ensure the input is a string
#         return "non-personal"
#     classes = data_classes.split(",")  # Split in case of multiple labels
#     for cls in classes:
#         if class_mapping.get(cls.strip(), "non-personal") == "personal":
#             return "personal"
#     return "non-personal"

def classify_data(data_classes):
    if data_classes is None:
        return "non-personal"  # Explicitly handle missing values
    data_classes = str(data_classes)  # Convert to string if possible
    classes = data_classes.split(",")  
    for cls in classes:
        if class_mapping.get(cls.strip(), "non-personal") == "personal":
            return "personal"
    return "non-personal"


# Function to classify an existing DataFrame
def classify_dataframe(df):
    df["Label"] = df["label"].apply(classify_data)
    df.rename(columns={"label": "Original labels"}, inplace=True)
    return df

In [52]:
Train_dessi_labels.loc[Train_dessi_labels['Original labels']=='ID_Card']

      Original labels     Label
694           ID_Card  personal
2003          ID_Card  personal
2006          ID_Card  personal
2153          ID_Card  personal
2936          ID_Card  personal
3498          ID_Card  personal
3878          ID_Card  personal
4065          ID_Card  personal
4270          ID_Card  personal
4292          ID_Card  personal
4731          ID_Card  personal
5386          ID_Card  personal
5658          ID_Card  personal
6153          ID_Card  personal
6650          ID_Card  personal
7893          ID_Card  personal
8904          ID_Card  personal
10445         ID_Card  personal
10629         ID_Card  personal
11520         ID_Card  personal
11851         ID_Card  personal
12713         ID_Card  personal
12989         ID_Card  personal
13031         ID_Card  personal
13439         ID_Card  personal
13603         ID_Card  personal
13721         ID_Card  personal
13932         ID_Card  personal
14055         ID_Card  personal
14166         ID_Card  personal
14336         ID_Card  personal
14594         ID_Card  personal
14983         ID_Card  personal
15119         ID_Card  personal
15607         ID_Card  personal
16307         ID_Card  personal
16598         ID_Card  personal
17026         ID_Card  personal
17150         ID_Card  personal
17418         ID_Card  personal
17632         ID_Card  personal
18439         ID_Card  personal
18673         ID_Card  personal

In [51]:
Train_label_mapped1 = classify_dataframe(Train_dessi_labels)

In [57]:
Train_label_mapped1.loc[Train_label_mapped1['Label']=="personal"]['Original labels'].unique()

array(['Person', 'Organization,Person', 'Phone_number',
       'Address,Geolocation', 'Address', 'Email', 'NIN', 'Date,NIN',
       'SWIFT/BIC', 'NIN,Email', 'Email,Phone_number', 'Passport',
       'Phone_number,NIN', 'CCN', 'Nationality', 'Email,Person', 'Race',
       'Email,NIN', 'Person,NIN', 'Person,Organization', 'Person,Email',
       'Geolocation,Address', 'NIN,Date', 'Address,Email', 'IBAN',
       'Email,Address', 'Gender', 'NIN,Person', 'Phone_number,Email',
       'NIN,Phone_number', 'Sexuality', 'ID_Card', 'Religion',
       'Address,Person,Phone_number', 'Address,Phone_number',
       'Organization,Phone_number', 'Address,Person',
       'Organization,Address'], dtype=object)

In [55]:
# Run once or run by starting from the begining of the script
# Train_label_mapped = classify_dataframe(Train_dessi_labels)

In [56]:
Train_label_mapped1['Label'].value_counts()

Label
personal        10195
non-personal     8621
Name: count, dtype: int64

In [58]:
New_train_labels = Train_label_mapped1['Label']

In [59]:
New_train_labels.to_csv('train_labels1.csv', index=False)

In [62]:
Test_label_mapped = classify_dataframe(Test_dessi_labels)

In [87]:
Test_label_mapped.loc[Test_label_mapped['Original labels']=='Phone_number']

     Original labels     Label
1       Phone_number  personal
3       Phone_number  personal
8       Phone_number  personal
9       Phone_number  personal
28      Phone_number  personal
...              ...       ...
6227    Phone_number  personal
6228    Phone_number  personal
6252    Phone_number  personal
6261    Phone_number  personal
6262    Phone_number  personal

[695 rows x 2 columns]

 See Everything in one

In [88]:
Testcheck = Test_label_mapped.copy()
Testcheck1 = pd.DataFrame()
Testcheck1['Features'] = Test_dessi.columns

In [89]:
Testcheck1['Original labels'] = Testcheck['Original labels']
Testcheck1['label'] = Testcheck['Label']

In [ ]:
Testcheck1[Testcheck1['Original labels']=='Date']

                   Features Original labels         label
21             eqlpgrkeonmy            Date  non-personal
33              birthday_id            Date  non-personal
70          date_of_birth.1            Date  non-personal
93        call_end_datetime            Date  non-personal
99             qgnkghfbptxb            Date  non-personal
...                     ...             ...           ...
6243   call_end_datetime.11            Date  non-personal
6245       lastlogindateb.8            Date  non-personal
6246           ktgjrkveeoeb            Date  non-personal
6248           npygcvxzyvwz            Date  non-personal
6271  date_account_closed.6            Date  non-personal

[477 rows x 3 columns]

In [93]:
Test_dessi['eqlpgrkeonmy']

0     11-17
1     12-99
2     08-73
3     11-73
4     05-13
      ...
95    05-09
96    01-17
97    09-74
98    02-72
99    02-01
Name: eqlpgrkeonmy, Length: 100, dtype: object

In [67]:
Test_label_mapped.loc[Test_label_mapped['Label']=="non-personal"]['Original labels'].unique()

array(['GPE', 'Other_data', 'Geolocation', 'Date', 'Organization'],
      dtype=object)

In [65]:
Test_label_mapped['Label'].value_counts()

Label
personal        3378
non-personal    2894
Name: count, dtype: int64

In [68]:
New_test_labels = Test_label_mapped['Label']

In [69]:
New_test_labels.to_csv('test_labels1.csv',index=False)

In [70]:
dev_label_mapped = classify_dataframe(dev_dessi_labels)

In [71]:
dev_label_mapped['Label'].value_counts()

Label
personal        3493
non-personal    2779
Name: count, dtype: int64

In [73]:
dev_label_mapped.loc[dev_label_mapped['Label']=="personal"]['Original labels'].unique()

array(['NIN', 'Phone_number', 'Date,NIN', 'NIN,Date', 'Address', 'Person',
       'Person,NIN', 'Phone_number,Email', 'Person,Email', 'Email',
       'Organization,Person', 'Race', 'NIN,Email', 'Passport',
       'Address,Geolocation', 'ID_Card', 'SWIFT/BIC',
       'Geolocation,Address', 'Nationality', 'Email,NIN', 'NIN,Person',
       'Religion', 'NIN,Phone_number', 'IBAN', 'Email,Person',
       'Phone_number,NIN', 'Person,Organization', 'Address,Email',
       'Gender', 'Sexuality', 'Email,Phone_number', 'Email,Address',
       'Person,Phone_number', 'CCN', 'Person,Date',
       'Organization,Address'], dtype=object)

In [74]:
New_dev_labels = dev_label_mapped['Label']

In [75]:
New_dev_labels.to_csv('dev_labels1.csv',index=False)

In [76]:
Test_labels_correct = pd.read_csv('/home/aagisha/Documents/PhD Albert/CodingPhDStart1/WorkshopArticle_1/Experiments/Personal-Detection/datasets/dessi/DeSSI_v2/test_labels1.csv')

In [78]:
Test_labels_correct.value_counts()

Label
personal        3378
non-personal    2894
Name: count, dtype: int64

In [79]:
Train_labels_correct =pd.read_csv('/home/aagisha/Documents/PhD Albert/CodingPhDStart1/WorkshopArticle_1/Experiments/Personal-Detection/datasets/dessi/DeSSI_v2/train_labels1.csv')

In [80]:
Train_labels_correct.value_counts()

Label
personal        10195
non-personal     8621
Name: count, dtype: int64

In [81]:
dev_labels_correct =pd.read_csv('/home/aagisha/Documents/PhD Albert/CodingPhDStart1/WorkshopArticle_1/Experiments/Personal-Detection/datasets/dessi/DeSSI_v2/dev_labels1.csv')

In [82]:
dev_labels_correct.value_counts()

Label
personal        3493
non-personal    2779
Name: count, dtype: int64

In [86]:
pd.read_csv('/home/aagisha/Documents/PhD Albert/CodingPhDStart1/WorkshopArticle_1/Experiments/CASSED-main/datasets/dessi_personal_standard/train_labels.csv').value_counts()

Label
personal        10195
non-personal     8621
Name: count, dtype: int64

In [19]:
# import pandas as pd

# # Define the mapping of classes to "Personal" and "Non-Personal"
# class_mapping = {
#     "Other data": "Non-Personal",
#     "Phone number": "Personal",
#     "Address": "Personal",
#     "Person": "Personal",
#     "Email": "Personal",
#     "NIN": "Personal",
#     "Date": "Non-Personal",
#     "Organization": "Non-Personal",
#     "GPE": "Non-Personal",
#     "Geolocation": "Non-Personal",
#     "SWIFT/BIC": "Personal",
#     "IBAN": "Personal",
#     "Passport": "Personal",
#     "Religion": "Personal",
#     "CCN": "Personal",
#     "ID Card": "Personal",
#     "Sexuality": "Personal",
#     "Gender": "Personal",
#     "Nationality": "Personal",
#     "Race": "Personal"
# }

# # Function to classify a given class or combination of classes into "Personal" or "Non-Personal"
# def classify_data(data_classes):
#     classes = data_classes.split(",")  # Split in case of multiple labels
#     for cls in classes:
#         if class_mapping.get(cls.strip(), "Non-Personal") == "Personal":
#             return "Personal"
#     return "Non-Personal"

# # Function to create a DataFrame with classification
# def classify_dataframe(semantic_labels):
#     df = pd.DataFrame(semantic_labels, columns=["Original labels"])
#     df["Label"] = df["Original labels"].apply(classify_data)
#     return df

# # Example usage
# example_classes = ["Phone number", "Organization", "CCN", "Date", "Race", "Geolocation,Address"]
# df_result = classify_dataframe(example_classes)

# # Print results
# print(df_result)